language: node_js
node_js:
- '8'
- '9'
script: 'yarn test && yarn build && TEST_DIST=1 yarn test'
jobs:
  include:
    - stage: browsertest
      # Disable browsertest stage on pull requests, since encrypted environment variables
      # are not available in such untrusted build jobs
      if: repo = automerge/automerge AND type != pull_request
      node_js: 9
      script: karma start karma.sauce.js
      env:
        - SAUCE_USERNAME=automerge
        - secure: AcvrV6Bh2aJ0Djs9+Vr+/XHOI7z6WYkuPtGh9JKVcDI+DMRiXOk8tXac0BaQ8cJ+ZsOqBvAAf/2TN3ft+ByNHKIMeI655fUaVrSBwqZakGliedmxgR5TOGOQwKtYlR3vwKIXtPaUddtqT7cI/qcBZjYs6hqNZOtw1v+yq92fKGFCwgUf6Au0SypL9gAPhLNmQhT4maadNhiZaOFXSneUndgBTgBabJ/75DU+jE1SKRnmjHdXqRZkqgcRhe9Kf0CykbuV6+SfppINkaUyVXn5g1GyN86Wb5gAZkjeCIlzUtFeWlEnkGJdEqLPSxfIPZk91SRHsR7MVU901+C/HOO5dc33zbGatgPw3TZ6Nlzxpbv5lpYke/4qoChoxclRMgIduBW8igOVi3RFveE3kLy8Jo4ftvWJYfwtIpemV57HQ2ym1z2KL6US77G+xLfrot5eXWFKKmfmX+qFxL0IdNRbJP2fw5QXTy5iPugoveExT/pow5ywbsJqdDbbazEQ0mNiizpV3EiTs1T6hx31h6C8eUUUadSyeyJli9tSfWe0t06Cs4Xu099BXNuenN6jv7j7JEPhNQzX0wb1azU6W1TKGm1qfQ2BWzOznR/zPtfVpd3t5fFpREDL48+jmKPOg0THqEAPNnn7UNtmdL/eFRKzi076c4sHaeRFwhXryqwjBlw=
      addons:
        sauce_connect: true
    - stage: deploy
      node_js: 9
      script: yarn install
      deploy:
        provider: npm
        skip_cleanup: true
        email: martin@kleppmann.com
        api_key:
          secure: Z6gZZAaoKfJKPZyzhraqOQwkExo9v3d9/rSpOhZ/ZR4npXoiJiV5YT6G1jIgEcxlac0veoBQIuXm3G1TgtLQD9kcrpAI3GiWPr1i+KAE55ILDS6Q9c42KEAI99vIECGp/qp19qg9gqfsjlOrQ0cbbQz/AK0/XiE5qFJ5Bw4WKytJTGQqr9m6m73Ycq21VytVTH2TyP5AubWN1zmSc/1+/JxAkEVuS7TG1C+FOGuGtn6X4WL64mBjKVhG+ZCXhCXajinhTvSDKBGcvi1EBafwNKqMRbUhEZqy+8c/pYD0ICPj69i9mb+GRQPhq8Sn93KYRNXYQX1vYZVSH6PeYxMQXpNJXxobJjB7YMhBToJmaEUiyw8edhu0koxlmQMVHcARDAGvKxyzi6o6B4grzgiFlcgi2jeyoAH9eo/GvkoLd8tgA7JErelIjzagXUW0lIQ75GmpZcR8ivHTVUDC4EfsvkWmLGW15gmOHrZwaYHuYpYwKJ07F+UKBjnzdAxyIRk6ZJxCdiWsKK/bCRqTtTf1sf8GUjzgc8J3DM4ixO4ad9AaeUigeBWhpwaSVrC8pRKNVxacve5ehihDaGk3S1sINSDSiGIaPSHcyMrdeD9EAGdNmVLkXxT++N0lu3KZEG+guBX216FxIbRoQ7okuRkDZzlXOdRojh28MPEH2+S1Y3k=
        on:
          tags: true
          repo: automerge/automerge
